
version: '3.0'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:50001
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'  
      POSTGRES_DB: 'postgres' 
    volumes:
      - ./pData:/var/lib/postgresql/data
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s   
    
  
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5001"
    restart: always
    image: app:2.0
    depends_on:
      db:
        condition: service_healthy    
    links: 
        - db
