apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "500m"
    limits.memory: 512Mi